version: 0.2

phases:
  install:
    commands:
      - npm install
      - apt-get update
      - apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
  pre_build:
    commands:
      -CI=true npm test
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build

